version: '3.4'

services:

  devkit.gateway:
    image: devkit.gateway
    build:
      context: .
      dockerfile: src/apps/core/api/gateway/Devkit.Gateway/Dockerfile

  devkit.security:
    image: devkit.security
    build:
      context: .
      dockerfile: src/apps/core/api/security/Devkit.Security/Dockerfile

networks:
  default:
    external:
      name: base_devkit.net
