version: '3.4'

services:

  devkit.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DEVKIT_GATEWAY_TYPE=mobile
      - OCELOT_CONFIG_PATH=/app/configs/
      - ASPNETCORE_HTTPS_PORT=44301
    ports:
      - "8001:80"
      - "44301:443"
    volumes:
      - ./configs/gateway:/app/configs:ro

  devkit.security:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      ###############################################
      # Add 3rd party authentication provider info. #
      ###############################################
      - "GOOGLE_CLIENT_ID=Add Google client id"
      - "GOOGLE_SECRET=Add Google secret"
      - "FACEBOOK_CLIENT_ID=Add Facebook client id"
      - "FACEBOOK_SECRET=Add Facebook secret"
    ports:
      - "8002:80"
      - "44302:443"
    volumes:
      - ./configs/services/security-api/:/app/configs:ro
