apiVersion: v1
kind: Service
metadata:
  namespace: devkit-base-ns
  name: elasticsearch-service
  labels:
    name: elasticsearch-service
    app: devkit-app
    tier: base
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    name: elasticsearch-pod
    app: devkit-app
    tier: base
    