apiVersion: v1
kind: Service
metadata:
  namespace: devkit-base-ns
  name: kibana-service
  labels:
    name: kibana-service
    app: devkit-app
    tier: base
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30102
  selector:
    name: kibana-pod
    app: devkit-app
    tier: base
