apiVersion: v1
kind: Service
metadata:
  namespace: devkit-base-ns
  name: mongo-service
  labels:
    name: mongo-service
    app: devkit-app
    tier: base
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-pod
    app: devkit-app
    tier: base