version: "3.5"

services:
   
  devkit.mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devkit
      - MONGO_INITDB_ROOT_PASSWORD=devkit_password
    volumes:
      - devkit-mongodb:/data/db/

  devkit.consul:
    ports:
      - "8081:8500"
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0

  devkit.portainer:
    ports:
      - "8082:9000"
    restart: always
    volumes:
      - devkit-portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  devkit.rabbitmq:
    ports:
      - "8083:15672"
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    volumes:
      - devkit-rabbitmq:/var/lib/rabbitmq/mnesia

  devkit.mongoclient:
    ports:
      - "8084:3000"
    volumes:
      - devkit-mongoclient:/data/db mongoclient/mongoclient
    
  devkit.elasticsearch:
    ports:
      - 9200:9200
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    volumes:
      - devkit-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    
  devkit.kibana:
    ports:
      - 5601:5601
    build:
      context: kibana
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://devkit.elasticsearch:9200

volumes:

  devkit-mongoclient:
  devkit-mongodb:
  devkit-rabbitmq:
  devkit-elk:
  devkit-portainer:
  devkit-rabbitmq:
  devkit-elasticsearch: