version: "3.5"

services:

  devkit.mongodb:
    image: devkit.mongodb
    container_name: devkit.mongodb
    build:
      context: .
      dockerfile: mongodb/Dockerfile
    restart: unless-stopped
    networks:
      - devkit.net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devkit
      - MONGO_INITDB_ROOT_PASSWORD=devkit_password
    volumes:
      - devkit-mongodb:/data/db/

  devkit.consul:
    image: devkit.consul
    container_name: devkit.consul
    build:
      context: .
      dockerfile: consul/Dockerfile
    restart: unless-stopped
    networks:
      - devkit.net
    ports:
      - "8081:8500"
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0

  devkit.portainer:
    image: devkit.portainer
    container_name: devkit.portainer
    build:
      context: .
      dockerfile: portainer/Dockerfile
    restart: unless-stopped
    networks:
      - devkit.net
    ports:
      - "8082:9000"
    volumes:
      - devkit-portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  devkit.rabbitmq:
    image: devkit.rabbitmq
    container_name: devkit.rabbitmq
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    restart: unless-stopped
    networks:
      - devkit.net
    ports:
      - "8083:15672"
    volumes:
      - devkit-rabbitmq:/var/lib/rabbitmq/mnesia

  devkit.mongoclient:
    image: devkit.mongoclient
    container_name: devkit.mongoclient
    build:
      context: .
      dockerfile: mongoclient/Dockerfile
    restart: unless-stopped
    networks:
      - devkit.net
    ports:
      - "8084:3000"
    volumes:
      - devkit-mongoclient:/data/db mongoclient/mongoclient
     
  devkit.elasticsearch:
    container_name: devkit.elasticsearch
    image: devkit.elasticsearch
    restart: unless-stopped
    networks:
      - devkit.net
    ports:
      - 9200:9200
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    volumes:
      - devkit-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    
  devkit.kibana:
    container_name: devkit.kibana
    image: devkit.kibana
    restart: unless-stopped
    depends_on:
      - devkit.elasticsearch
    networks:
      - devkit.net    
    ports:
      - 5601:5601
    build:
      context: kibana
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://devkit.elasticsearch:9200

networks:
  devkit.net:
    driver: bridge
    
volumes:
  devkit-mongoclient:
  devkit-mongodb:
  devkit-rabbitmq:
  devkit-elk:
  devkit-portainer:
  devkit-elasticsearch:
