version: '3.4'

services:

  devkit.gateway:
    image: devkit.gateway
    build:
      context: .
      dockerfile: apps/core/api/gateway/Devkit.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=44301
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DEVKIT_GATEWAY_TYPE=mobile
      - OCELOT_CONFIG_PATH=/app/configs/
      - ENABLE_SERVICE_REGISTRY=true
      - ENABLE_SWAGGER=true
      - LOG_INDEX=devkit.gateway
      - LOG_SINK=elk
      - SERVICE_BUS_TYPE=amqp
      - SSL_CERT=./https/aspnetapp.pfx
      - SSL_PASSWORD=Passw0rd123$$
    ports:
      - "8001:80"
      - "44301:443"
    volumes:
      - ./configs/gateway:/app/configs:ro
      - ./configs/infrastructure/:/app/infrastructure:ro
      - ./https/:/app/https

  devkit.security:
    image: devkit.security
    build:
      context: .
      dockerfile: apps/core/api/security/Devkit.Security/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ENABLE_SWAGGER=true
      - ENABLE_SERVICE_REGISTRY=true
      - LOG_INDEX=devkit.security
      - LOG_SINK=elk
      - SERVICE_BUS_TYPE=amqp
      - SSL_CERT=./https/aspnetapp.pfx
      - SSL_PASSWORD=Passw0rd123$$
      ###############################################
      # Add 3rd party authentication provider info. #
      ###############################################
      - "GOOGLE_CLIENT_ID=Add Google client id"
      - "GOOGLE_SECRET=Add Google secret"
      - "FACEBOOK_CLIENT_ID=Add Facebook client id"
      - "FACEBOOK_SECRET=Add Facebook secret"
    ports:
      - "8002:80"
      - "44302:443"
    volumes:
      - ./configs/services/security-api/:/app/configs:ro
      - ./configs/infrastructure/:/app/infrastructure:ro
      - ./https/:/app/https

  devkit.file-store:
    image: devkit.file-store
    build:
      context: .
      dockerfile: apps/core/api/file-store/Devkit.FileStore/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ENABLE_SWAGGER=true
      - ENABLE_SERVICE_REGISTRY=true
      - LOG_INDEX=devkit.file-store
      - LOG_SINK=elk
      - SERVICE_BUS_TYPE=amqp
      - SSL_CERT=./https/aspnetapp.pfx
      - SSL_PASSWORD=Passw0rd123$$
    ports:
      - "8003:80"
      - "44303:443"
    volumes:
      - ./configs/services/file-store-api/:/app/configs:ro
      - ./configs/infrastructure/:/app/infrastructure:ro
      - ./https/:/app/https

networks:
  default:
    external:
      name: base_devkit.net
