apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devkit-api-ns
  name: file-store-deploy
  labels:
    name: file-store-deploy
    app: devkit-app
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:      
      name: file-store-pod
      app: devkit-app
      tier: api
  template:
    metadata:
      namespace: devkit-api-ns
      name: file-store-pod
      labels:
        name: file-store-pod
        app: devkit-app
        tier: api
    spec:
      containers:
        - name: filestore
          image: devkit.filestore:latest
          ports:
            - containerPort: 443
    
