apiVersion: v1
kind: Service
metadata:
  namespace: devkit-api-ns
  name: gateway-service
  labels:
    name: gateway-service
    app: devkit-app
    tier: apiVersion
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
  selector:
    name: gateway-pod
    app: devkit-app
    tier: api