apiVersion: v1
kind: Service
metadata: 
  namespace: devkit-api-ns
  name: security-service
  labels:
    name: security-service
    app: devkit-app
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
  selector:
    name: security-pod
    app: devkit-app
    tier: api