version: '3.4'

services:
  devkit.file-store:
    image: devkit.file-store:dev
    container_name: Devkit.FileStore
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Devkit.FileStore"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_devkit.file-store$
    volumes:
      - F:\Source\Repos\devkit-microservice-framework\src\apps\core\api\file-store\Devkit.FileStore:/app
      - F:\Source\Repos\devkit-microservice-framework\src:/src
      - C:\Users\ryana\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_devkit.file-store$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_devkit.file-store$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  devkit.gateway:
    image: devkit.gateway:dev
    container_name: Devkit.Gateway
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Devkit.Gateway"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_devkit.gateway$
    volumes:
      - F:\Source\Repos\devkit-microservice-framework\src\apps\core\api\gateway\Devkit.Gateway:/app
      - F:\Source\Repos\devkit-microservice-framework\src:/src
      - C:\Users\ryana\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_devkit.gateway$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_devkit.gateway$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  devkit.security:
    image: devkit.security:dev
    container_name: Devkit.Security
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Devkit.Security"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_devkit.security$
    volumes:
      - F:\Source\Repos\devkit-microservice-framework\src\apps\core\api\security\Devkit.Security:/app
      - F:\Source\Repos\devkit-microservice-framework\src:/src
      - C:\Users\ryana\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_devkit.security$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_devkit.security$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
